import { createHash } from "node:crypto"
import { createReadStream } from "node:fs"
import type { ResolvedSpec } from "./types.ts"

export function sha256(data: Buffer | string): string {
  return createHash("sha256").update(data).digest("hex")
}

export async function sha256File(path: string): Promise<string> {
  return new Promise((resolve, reject) => {
    const hash = createHash("sha256")
    const stream = createReadStream(path)
    stream.on("data", (chunk) => hash.update(chunk))
    stream.on("error", reject)
    stream.on("end", () => resolve(hash.digest("hex")))
  })
}

/**
 * Identity of a spec: everything that would change the generated image.
 * Project root, `outFile`, committed `source`, and `tags` are deliberately excluded;
 * moving a checkout, renaming the destination, swapping the committed art a
 * `mount` places, or retagging should not regenerate art.
 *
 * Generator-specific parameters are hashed only where they apply, and are
 * left `undefined` otherwise so `JSON.stringify` drops the key entirely.
 * That matters: adding a field unconditionally rewrites the hash of every
 * spec in every existing lockfile, and each one then reports as `stale` and
 * invites a full regeneration of art that never changed. Adding `palette`
 * unconditionally did exactly that once already.
 */
export function specHash(
  spec: Omit<ResolvedSpec, "specHash" | "root" | "outFile" | "quality" | "source" | "tags" | "remoteId">,
  styleImageHashes: string[],
  providerOptionIdentity: unknown = spec.providerOptions,
  providerInputIdentity: unknown = spec.providerInputs ?? {},
): string {
  return sha256(
    JSON.stringify({
      // Preserve every existing PixelLab hash while making a provider switch
      // invalidate the spec. Older manifests implicitly mean pixellab.
      provider: spec.provider === "pixellab" ? undefined : spec.provider,
      providerOptions:
        providerOptionIdentity &&
        (typeof providerOptionIdentity !== "object" || Object.keys(providerOptionIdentity).length > 0)
          ? providerOptionIdentity
          : undefined,
      providerInputs:
        providerInputIdentity &&
        (typeof providerInputIdentity !== "object" || Object.keys(providerInputIdentity).length > 0)
          ? providerInputIdentity
          : undefined,
      generator: spec.generator,
      prompt: spec.prompt,
      width: spec.width,
      height: spec.height,
      view: spec.view,
      outline: spec.outline ?? null,
      shading: spec.shading ?? null,
      detail: spec.detail ?? null,
      seed: spec.seed ?? null,
      palette: spec.palette,
      // `noBackground` only reaches the wire for pixflux and uiAsset; the
      // tile fields are undefined for every other generator. `tileSize` is
      // intentionally absent; width/height are derived from it, so it is
      // already covered.
      noBackground:
        spec.generator === "pixflux" || spec.generator === "uiAsset" || spec.generator === "uiElement" ||
          spec.provider !== "pixellab"
          ? spec.noBackground
          : undefined,
      tileType: spec.tileType,
      tileView: spec.tileView,
      tileFeature: spec.tileFeature,
      outlineMode: spec.outlineMode,
      isometricTileSize: spec.isometricTileSize,
      isometricTileShape: spec.isometricTileShape,
      uiPieces: spec.uiPieces,
      uiElements: spec.uiElements,
      uiColorPalette: spec.uiColorPalette,
      styleImages: styleImageHashes,
      // A character family: the engine and rotations of a base, the parent's
      // generated bytes for a state or animation (so a regenerated parent
      // makes its children stale), and each shape's own settings.
      character: spec.character
        ? {
            kind: spec.character.kind,
            mode: spec.character.mode,
            directions: spec.character.directions,
            template: spec.character.template,
            parent: spec.character.parentAssetId,
            parentSha256: spec.character.parentSha256 ?? null,
            state: spec.character.state,
            // Pose images enter as their hashes, never their paths.
            animation: spec.character.animation
              ? {
                  ...spec.character.animation,
                  startFrame: spec.character.animation.startFrame?.sha256,
                  endFrame: spec.character.animation.endFrame?.sha256,
                }
              : undefined,
            // Absent keys keep the hashes of manifests that never set these.
            proportions: spec.character.proportions,
            textGuidanceScale: spec.character.textGuidanceScale,
            isometric: spec.character.isometric,
            enhancePrompt: spec.character.enhancePrompt,
            styleTraits: spec.character.styleTraits,
            reference: spec.character.reference
              ? Object.fromEntries(Object.entries(spec.character.reference).map(([direction, image]) => [direction, image.sha256]))
              : undefined,
            concept: spec.character.concept?.sha256,
            styleAnchor: spec.character.styleAnchor
              ? { of: spec.character.styleAnchor.assetId, sha256: spec.character.styleAnchor.sha256 }
              : undefined,
          }
        : undefined,
      // An objectPro family: same shape as character above, minus the
      // fields it has none of (mode/template/proportions/isometric/concept/
      // styleAnchor) — see ResolvedObjectPro.
      objectPro: spec.objectPro
        ? {
            kind: spec.objectPro.kind,
            directions: spec.objectPro.directions,
            parent: spec.objectPro.parentAssetId,
            parentSha256: spec.objectPro.parentSha256 ?? null,
            state: spec.objectPro.state,
            animation: spec.objectPro.animation
              ? {
                  ...spec.objectPro.animation,
                  startFrame: spec.objectPro.animation.startFrame?.sha256,
                  endFrame: spec.objectPro.animation.endFrame?.sha256,
                }
              : undefined,
            styleTraits: spec.objectPro.styleTraits,
            reference: spec.objectPro.reference?.sha256,
          }
        : undefined,
      // A mirror's bytes come from its source's recorded outputs; the plan
      // compares those directly, so only the choice of source is identity.
      mirror: spec.mirror ? { of: spec.mirror.sourceAssetId } : undefined,
      // The whole group's ordered descriptions, not just this asset's own —
      // any sibling's prompt changing, or a member being added or removed,
      // must mark every member stale together, since they all ride on one
      // submitted job with no way to amend it after the fact.
      batch: spec.batch ? { role: spec.batch.role, itemDescriptions: spec.batch.itemDescriptions, index: spec.batch.index } : undefined,
      revision: spec.revision
        ? {
            mode: spec.revision.mode,
            from: spec.revision.sourceAssetId,
            sourceSha256: spec.revision.sourceSha256,
            maskSha256: spec.revision.maskSha256,
            strength: spec.revision.strength,
            numColors: spec.revision.numColors,
            paletteImageSha256: spec.revision.paletteImageSha256,
            dithering: spec.revision.dithering,
            ditheringStrength: spec.revision.ditheringStrength,
            frames: spec.revision.frames,
            fps: spec.revision.fps,
            lastFrameSha256: spec.revision.lastFrameSha256,
            direction: spec.revision.direction,
            enhancePrompt: spec.revision.enhancePrompt,
            keypointsSha256: spec.revision.keypointsSha256,
            skeletonTemplate: spec.revision.skeletonTemplate,
            description: spec.revision.description,
          }
        : undefined,
    }),
  )
}
